In [17]:
import numpy as np

In [27]:
def rastrigin(x, A=10):
    """NumPy Rastrigin test function"""
    return -np.sum(A - A * np.cos(2 * np.pi * x) + x**2, axis=0)

In [18]:
lamba = 5
mu = 3

In [19]:
population = np.array([[0.,1.], [1., 1.], [0., 0.]])
population.shape

(3, 2)

In [20]:
offspring = population[np.array([0, 0, 1, 2, 2])]
print(offspring)
offspring.shape

[[0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


(5, 2)

In [21]:
# Select the last column of offspring elements
offspring[:, -1]

array([1., 1., 1., 0., 0.])

In [22]:
# update last column of offspring by a Gaussian Normal with given mean and std_dev = .2 => update sigma!
offspring[:, -1] = np.random.normal(loc=offspring[:, -1], scale=.2)
offspring

array([[ 0.        ,  0.94045693],
       [ 0.        ,  1.25418163],
       [ 1.        ,  0.95210701],
       [ 0.        , -0.00828841],
       [ 0.        ,  0.09431866]])

In [23]:
# Those elements for which the last column is < threshold, update it to threshold
offspring[offspring[:, -1] < 1e-5, -1] = 1e-5
offspring

array([[0.00000000e+00, 9.40456934e-01],
       [0.00000000e+00, 1.25418163e+00],
       [1.00000000e+00, 9.52107007e-01],
       [0.00000000e+00, 1.00000000e-05],
       [0.00000000e+00, 9.43186625e-02]])

In [25]:
# Update all previous columns (except the last one which was already updated) [reshape -1, keep compatible dimension]
offspring[:, 0:-1] = np.random.normal(loc=offspring[:, 0:1], scale=offspring[:, -1].reshape(-1, 1))
offspring

array([[ 5.90309869e-01,  9.40456934e-01],
       [-1.09418711e+00,  1.25418163e+00],
       [ 2.50918104e+00,  9.52107007e-01],
       [-1.97008389e-06,  1.00000000e-05],
       [ 1.52342279e-01,  9.43186625e-02]])

In [31]:
fitness = rastrigin(offspring[:, 0:-1])
fitness

array([-52.22354212])

In [33]:
offspring = offspring[fitness.argsort()]
offspring

array([[0.59030987, 0.94045693]])

In [34]:
# get last (best) mu elements in offspring to generate the new population
pop = np.copy(offspring[-mu:])
pop

array([[0.59030987, 0.94045693]])

In [40]:
population[-2:]

array([[1., 1.],
       [0., 0.]])